#ifndef LOG_ENUM_USB_H
#define LOG_ENUM_USB_H
/*=======================================================================*//**
 * @file      usb_enum_log.h
 * @author    kameya
 * @date      08/21/2017
 *
 * @brief     USB ENUM LOG API header
 *
 * @details   This file contains the implementation of enum based ulog APIs.
 *
 * @note      Copyright 2017 Qualcomm Technologies Inc.
 *            All Rights Reserved.
 *            Qualcomm Confidential and Proprietary
 * 
*//*========================================================================*/

//----------------------------------------------------------------------------
// Include Files
//----------------------------------------------------------------------------
#include "comdef.h" // common defines - basic types as uint32 etc
#include "log.h"

/*----------------------------------------------------------------------------
 * Preprocessor Definitions and Constants
 * -------------------------------------------------------------------------*/

/*----------------------------------------------------------------------------
 * Type Declarations
 * -------------------------------------------------------------------------*/
// Bits <31:29> : represents module USB = 0x1
// Bits <28:24> : represents sub-module
// Bits<28:24> = 0 = ERR
// Bits<28:24> = 1 = GEN
// Bits<28:24> = 2 = DBG
// Bits<28:24> = 3 = ENG


typedef enum usb_err_log
{
  usb_err_log_start = 0x10000000,
  //UTIL----------------------------------------------------------------------------------------------------------
  log_usb_event_enqueue__queue_full_D,
  log_usb_event_dequeue__queue_empty_D,
  log_usb_dsr_handle_ee_event__unknown_event_D,
  log_usb_isr_pwr_uninit__failed_to_dereg_interrupt_D_errcode_D,
  log_usb_ee_pwr_uninit__failed_to_dereg_interrupt_D_errcode_D,
  log_usb_isr_pwr_init__failed_to_reg_interrupt_D,
  log_usb_ee_pwr_init__failed_to_reg_interrupt_D,
  log_usb_malloc_internal__fail_size_D,
  log_usb_free__fail_addr_D,
  log_usb_print_meminfo__size_D,
  log_usb_isr_enqueue_ee_event__no_event,
  //AL_API----------------------------------------------------------------------------------------------------------
  log_usb_audio_lb_stream_enable__wrong_ifc_D,
  log_usb_client_notification__empty_client_id_D,
  log_usb_tx_complete__kill_cli_D,
  log_usb_tx_complete__fail_cli_D_trans_stats_D_len_D,
  log_usb_tx_complete__len_err_cli_D_tran_len_D_act_len_D,
  log_usb_rx_complete__fail_cli_D_trans_stats_D_len_D,
  log_usb_rx_complete__ZLP_cli_D,
  log_usb_al_hlos_bulk_init__usb_ctx_empty,
  log_usb_al_hlos_bulk_init__already_enum,
  log_usb_al_hlos_bulk_init__fail_D,
  log_usb_deregister_client__null_cli_ctx,
  log_usb_deregister_client__overflow_cli_D,
  log_usb_register_client__overflow_cli_D,
  log_usb_isoc_in__bad_input_client_ctx_D,
  log_usb_al_hlos_handle__ctx_not_exist,
  log_usb_isoc_out__bad_input_client_ctx_D,
  log_usb_close__null_cli_ctx,
  log_usb_open__bad_ifc_D,
  //FD----------------------------------------------------------------------------------------------------------
  log_usb_fd_alloc_bos_des__unknown_rev_D,
  log_usb_fd_notify__evt_unknown_evt_D,
  log_usb_fd_init__unknown_ifc_id_D,
  log_usb_fd_tx_pkt__null_ptr_client_id_D,
  log_usb_fd_tx_pkt__urb_active__client_D,
  log_usb_fd_tx_pkt__trans_error_client_D,
  log_usb_fd_rx_pkt__null_ptr_client_id_D,
  log_usb_fd_rx_pkt__urb_active__client_id_D,
  log_usb_fd_rx_pkt__tran_error_client_D,
  log_usb_fd_cancel_transfer_dir__client_D_not_open,
  log_usb_fd_cancel_transfer_dir__cancel_failed,
  log_usb_fd_set_core__wrong_id_D,
  log_usb_hid_notify_speed__bad_spd_D,
  log_usb_hid_handle_get_req__wrong_report_D,
  log_usb_hid_handle_get_req__unknown_desc_D,
  log_usb_hid_handle_get_req__unknown_req_D,
  log_usb_hid_tx__drop_pending_report_D,
  log_usb_hid_tx__fail_report_D,
  log_usb_dfu_update_state__unknown_state_D,
  log_usb_dfu_handle_set_req__unknown_req_D,
  log_usb_dfu_timer_cb__signal_dfu_entry,
  log_usb_dfu_timer_cb__signal_dfu_exit,
  log_uac10_alloc_ac_cs_desc__unknown_node_D,
  log_uac20_alloc_ac_cs_desc__unknown_node_D,
  log_uac30_alloc_ac_cs_desc__unknown_node_D,
  log_usb_audio_notify_speed__unknown_spd_D,
  log_usb_audio_stream_set_ifc__stop_stream_ifc_D_alt_D,
  log_usb_audio_expl_fb_cb__zero_completion_length,
  log_usb_audio_start_expl_fb__stop_expl_ifc_D,
  log_usb_audio_start_stream__ifc_D,
  log_usb_audio_start_stream__si_us_D_slot_size_D_rate_D,
  log_usb_audio_stop_stream__ifc_D,
  log_usb_audio_alloc_as_desc__unknown_rev_D,
  log_usb_audio_alloc_ac_desc__unknown_rev_D,
  log_usb_audio_ctrl_init__unknown_profile_D,
  log_usb_fd_shutdown__null_fd,
  //DCD----------------------------------------------------------------------------------------------------------
  log_usb_dcd_find_ep__null_active_config,
  log_usb_dcd_set_interface__failed_to_set_ifc_D_alt_set_D,
  log_usb_dcd_set_interface__null_ep_dsc,
  log_handle_get_descriptor__dev_dsc_null,
  log_handle_get_descriptor__config_null,
  log_handle_get_descriptor__config_dsc_null,
  log_handle_get_descriptor__bos_dsc_null,
  log_handle_get_descriptor__string_dsc_null,
  log_handle_get_descriptor__devqual_dsc_null,
  log_handle_get_descriptor__other_speed_config_dsc_null,
  log_handle_get_descriptor__unknown_dsc_type_D,
  log_handle_setup_ifc__req_get_hid_class_desc,
  log_handle_setup_ifc__unknown_req_D,
  log_handle_setup_dev__unknown_req_D,
  log_handle_setup_ep__null_ep_line_D,
  log_handle_setup_std__unsupported_D,
  log_get_curr_ifc_alt_set__ifc_D,
  log_usb_dcd_handle_setup__unsupport_req_D,
  log_usb_dcd_handle_setup__stall_ep_req_D,
  log_usb_dcd_notify__default_case_D,
  log_usb_dcd_submit_urb__null_urb,
  log_usb_dcd_submit_urb__error_D,
  log_usb_dcd_ctrl_start_xfer__null_dcd,
  log_usb_dcd_shutdown__null_ptr,
  log_usb_dcd_set_core__null_ptr,
  log_usb_dcd_get_dci_ctx__null_ptr,
  log_usb_dcd_set_shutdown_mode__null_ptr,
  log_usb_dcd_get_shutdown_mode__null_ptr,
  log_usb_dcd_get_speed__null_ptr,
  log_usb_dcd_is_usb_config__null_ptr,
  log_usb_dcd_get_ctrl_urb_tx_transfer_status__null_ptr,
  log_usb_dcd_poll__null_ptr,
  log_usb_dcd_reset__null_ptr,
  log_usb_dcd_get_max_packset_size__null_ptr,
  log_usb_dcd_wakeup__null_ptr,
  log_handle_ep_halt__null_ptr,
  log_usb_dcd_handle_class_status3_req_ifc__req_len_D_act_len_D,
  log_usb_dcd_handle_class_status3_req_ifc__unknown_ifc_D,
  log_usb_dcd_handle_class_status3_req_ep__req_len_D_act_len_D,
  log_usb_dcd_handle_class_status3_req_ep__unknown_ifc_D,
  log_usb_dcd_handle_setup_class_ifc__unknown_ifc_D,
  log_usb_dcd_handle_get_class_ifc__unknown_ifc_D,
  log_usb_dcd_handle_get_class_ep__bad_ifc_id_D,
  log_usb_dcd_handle_setup_class__bad_recp_D,
  log_usb_dcd_vendor_out_cb__length_D_act_length_D,
  log_usb_dcd_handle_setup_class__failed,
  //DCI----------------------------------------------------------------------------------------------------------
  log_usb_dci_update_packet_size__unknown_speed_D,
  log_usb_dci_handle_test_mode__test_mode_D,
  log_usb_dci_init__null_ptr,
  log_usb_dci_core_init__write_ep_cmd_line_D,
  log_usb_dci_write_ep_cmd__ep_cmd_active_ep_index_D,
  log_usb_dci_write_ep_cmd__ep_cmd_invalid_type_D,
  log_usb_dci_write_ep_cmd__cmdact_us_delay_cnt_D,
  log_usb_dci_write_ep_cmd__cmd_timedout_delay_cnt_D,
  log_usb_dci_write_dev_cmd__cmd_active,
  log_usb_dci_write_dev_cmd__cmd_invalid_type_D,
  log_usb_dci_write_dev_cmd__cmdact_us_delay_cnt_D,
  log_usb_dci_write_dev_cmd__cmd_timedout_delay_cnt_D,
  log_usb_dci_handle_ep_event__missed_isoc_on_ep_D_dir_D_uF_D,
  log_usb_dci_handle_ep_event__xfer_nrdy_isoc_ep_D_dir_D_uf_D,
  log_usb_dci_handle_ep_event__sync_to_host_polling_at_rate_uF_D,
  log_usb_dci_handle_dev_event__event_buffer_overflow,
  log_usb_dci_poll_events__invalid_event,
  log_usb_dci_poll_events__unknown_event_type,
  log_usb_dci_handle_ctrl_transfers__xfer_complete_unexpected_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_in_setup_stage_dir_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_data_in_status2_stage_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_status2_wrong_dir_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_status3_wrong_dir_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_data_in_status3_stage_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_data_still_in_progress_D,
  log_usb_dci_handle_ctrl_transfers__invalid_event_status_D_ctrl_sta_D,
  log_usb_dci_handle_ctrl_transfers__uknown_event_D,
  log_usb_dci_handle_transfer_complete__ep_D_dir_D_out_of_bounds,
  log_usb_dci_handle_transfer_complete__null_ptr_urb_trb_phy_ep_num_D,
  log_usb_dci_handle_connect_done__unknown_speed_D,
  log_usb_dci_handle_connect_done__write_ep_cmd_fail,
  log_usb_dci_handle_connect_done__ctrl_sm_state_D,
  log_usb_dci_handle_suspend_entry__link_state_not_ls_u3,
  log_usb_dci_handle_suspend_entry__l2_enable_D__buf_empt_D__is_att_D,
  log_usb_dci_stall_endpoint__ep_D_dir_D_out_of_bounds,
  log_usb_dci_unstall_endpoint__ep_D_dir_D_out_of_bounds,
  log_usb_dci_config_endpoint__insuff_hw_resources,
  log_usb_dci_config_endpoint__write_ep_cmd_cfg_failure,
  log_usb_dci_config_endpoint__write_ep_cmd_failure,
  log_usb_dci_submit_trb_data__write_ep_cmd_failure,
  log_usb_dci_prepare_trbs__insuff_hw_rsrc_ep_D_dir_D_trb_idx_D,
  log_usb_dci_prepare_trbs__trb_swo_ep_D_dir_D_trb_idx_D,
  log_usb_dci_prepare_trbs__invalid_buff_size_D,
  log_usb_dci_transfer_data_request__size_too_large_D,
  log_usb_dci_transfer_data_request__ep_D_dir_D_out_of_bounds,
  log_usb_dci_ctrl_submit_request__ep_0_dir_D_out_of_bounds,
  log_usb_dci_transfer_request__failed_to_queue_xfer_ep_D_dir_D,
  log_usb_dci_cancel_transfer__ep_cmd_write_ep_D_dir_D,
  log_usb_dci_cancel_transfer__trb_hwo_ep_D_dir_D,
  log_usb_dci_cancel_transfer__zlp_trb_hwo_ep_D_dir_D,
  log_usb_dci_enter_lpm__link_state_D_phy_in_l2_D,
  log_usb_dci_poll_pwr_event__timed_out,
  log_usb_dci_handle_event__pwr_event_D,
  log_usb_dci_remote_wakeup_err_disabled,
  log_usb_dci_remote_wakeup__failure_poll_event_D,
  log_usb_dci_select_utmi_clk,
  log_usb_dci_submit_trb_data__next_uf_D_curr_uf_D,
  //CLIENT_CTX----------------------------------------------------------------------------------------------------------
  log_usb_cli_wrap_report__hid_fail__drop_cnt_D,
  //----------------------------------------------------------------------------------------------------------

} usb_err_log_t;

typedef enum usb_gen_log
{
  usb_gen_log_start = 0x11000000,
  //UTIL----------------------------------------------------------------------------------------------------------
  log_usb_dsr_handle_pwr_event__pwr_event_D,
  log_usb_isr_pwr_handle__pwr_event_D,
  //AL_API----------------------------------------------------------------------------------------------------------
  log_usb_audio_lb_stream_enable__ifc_id_D,
  log_usb_al_hlos_enum_complete__enum_flag_D,
  log_usb_al_hlos_disconnect_handler,
  log_usb_al_disconnect_cb,
  log_usb_al_notify_suspend__susflag_D,
  log_usb_al_hlos_bulk_init__exit,
  log_usb_register_client__cli_num_D,
  log_usb_shutdown,
  log_usb_al_hlos_handle__vbus_event_D,
  log_usb_al_hlos_handle__vbus_event_skip_is_enum_D,
  //FD----------------------------------------------------------------------------------------------------------
  log_usb_fd_alloc_bos_des__top_aud_rev_D_sel,
  log_usb_fd_notify__evt_config,
  log_usb_fd_notify__evt_unconfig,
  log_usb_fd_notify__evt_speed_D,
  log_usb_fd_notify__evt_addr_speed_D,
  log_usb_fd_notify__evt_disconnect,
  log_usb_fd_notify__evt_suspend,
  log_usb_fd_init,
  log_usb_hid_enum_complete__ifc_D,
  //DCD----------------------------------------------------------------------------------------------------------
  log_usb_dcd_fd_notify__null_fd_cb_notify,
  log_usb_dcd_set_interface__ifc_num_D_alt_set_D,
  log_usb_dcd_set_config__new_config_D,
  log_handle_setup_ifc__req_get_status_D,
  log_handle_setup_ifc__req_set_feature_remote_wakeup_D,
  log_handle_setup_ifc__req_clear_feature,
  log_handle_setup_dev__set_address_D,
  log_handle_setup_dev__set_sel_D,
  log_handle_setup_dev__set_descriptor,
  log_handle_setup_dev__set_config_D,
  log_usb_dcd_handle_reset,
  log_usb_dcd_handle_disconnect,
  log_usb_dcd_handle_suspend,
  log_usb_dcd_port_status_changed__spd_D,
  log_usb_dcd_init,
  log_handle_steup_class_ifc__length_D,
  log_handle_get_class_ifc__ifc_D,
  log_handle_get_class_ep__ifc_id_D,
  log_handle_setup_class_ep__ifc_id_D,
  log_handle_setup_class__dir_D_recp_D,
  log_handle_setup_vendor__dir_D_len_D,
  log_handle_ep_halt__ep_D,
  //DCI----------------------------------------------------------------------------------------------------------
  log_usb_dci_update_packet_size__max_packet_size_D,
  log_usb_dci_init,
  log_usb_dci_hw_init,
  log_usb_dci_core_init,
  log_usb_dci_event_buffer_init,
  log_usb_dci_set_run_stop__state_D,
  log_usb_dci_handle_ep_event__event,
  log_usb_dci_handle_ep_event__event_xfer_complete,
  log_usb_dci_handle_ep_event__event_xfer_in_progress,
  log_usb_dci_handle_ep_event__event_xfer_nrdy,
  log_usb_dci_handle_ep_event__event_rsv1,
  log_usb_dci_handle_ep_event__event_rsv2,
  log_usb_dci_handle_ep_event__event_ep_stream,
  log_usb_dci_handle_ep_event__event_ep_cmd_complete,
  
  log_usb_dci_handle_dev_event__disconnect_D,
  log_usb_dci_handle_dev_event__usb_reset_D,
  log_usb_dci_handle_dev_event__connect_done_D,
  log_usb_dci_handle_dev_event__usb_link_state_change_D,
  log_usb_dci_handle_dev_event__remote_wakeup_D,
  log_usb_dci_handle_dev_event__hibernation_request_D,
  log_usb_dci_handle_dev_event__suspend_entry_D,
  log_usb_dci_handle_dev_event__start_of_frame_D,
  log_usb_dci_handle_dev_event__erratic_error_D,
  log_usb_dci_handle_dev_event__cmd_complete_D,
  log_usb_dci_handle_dev_event__event_buffer_overflow_D,
  log_usb_dci_handle_dev_event__tst_lmp_rcvd_D,
  log_usb_dci_poll_events__event_D,
  log_usb_dci_handle_ctrl_transfers__xfer_complete_setup_D,
  log_usb_dci_handle_ctrl_transfers__xfer_complete_status_D,
  log_usb_dci_handle_ctrl_transfers__xfer_complete_data_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_data_dir_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_wrong_dir_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_status_in_data_stage_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_status2_D,
  log_usb_dci_handle_ctrl_transfers__xfer_nrdy_status3_D,
  log_usb_dci_handle_ctrl_transfers__event_ep_cmd_complete_D,
  log_usb_dci_handle_usb_reset,
  log_usb_dci_handle_connect_done,
  log_usb_dci_handle_usb_disconnect,
  log_usb_dci_get_link_state__state_D,
  log_usb_dci_handle_link_status_change__state_D,
  log_usb_dci_drive_remote_wakeup,
  log_usb_dci_handle_suspend_entry__link_state_D_is_ss_disabled_D,
  log_usb_dci_handle_suspend_entry__enter_suspended_state,
  log_usb_dci_handle_wakeup__out_of_suspended_state,
  log_usb_dci_handle_wakeup__link_state_ls_u3,
  log_usb_dci_set_address__address_D,
  log_usb_dci_stall_endpoint__ep_D,
  log_usb_dci_unstall_endpoint__ep_D,
  log_usb_dci_submit_trb_data__start_xfer_addrh_D_addrl_D,
  log_usb_dci_transfer_data_request__transfer_length_D,
  log_usb_dci_shutdown,
  log_usb_dci_get_speed_log_speed_D,
  log_usb_dci_set_max_packet_size__D,
  log_usb_dci_get_max_packet_size__D,
  log_usb_dci_handle_set_select,
  log_usb_enable_clocks__enable_D,
  log_usb_dci_select_phy_mode__phy_mode_D,
  //----------------------------------------------------------------------------------------------------------
} usb_gen_log_t;

typedef enum usb_dbg_log
{
  usb_dbg_log_start = 0x12000000,
  //UTIL----------------------------------------------------------------------------------------------------------
  log_usb_isr_hsphy_handle,
  log_usb_isr_dpse_handle,
  log_usb_isr_handle_1,
  log_usb_isr_handle_2,
  log_usb_isr_handle_3,
  log_usb_isr_pwr_handle__in_l2_pwr_event_D,
  log_usb_isr_pwr_handle__out_l2_pwr_event_D,
  log_usb_isr_pwr_handle__in_out_l2_pwr_event_D,
  log_usb_isr_pwr_handle__gsi_event_D,
  log_usb_isr_enqueue_ee_event__event_cnt_D__event_D,
  
  //AL_API----------------------------------------------------------------------------------------------------------
  log_usb_rx_complete__cancel_cli_D_len_D,
  log_usb_al_hlos_bulk_init__enter_spd_D,
  //FD----------------------------------------------------------------------------------------------------------
  log_usb_fd_notify__evt_D,
  log_usb_fd_tx_pkt__len_D,
  log_usb_fd_rx_pkt__len_D,
  log_usb_fd_set_core__id_D,
  log_usb_hid_notify_speed__spd_D,
  log_usb_hid_handle_get_req__report_D,
  log_usb_hid_handle_get_req__idle_D,
  log_usb_hid_handle_get_req__desc_D,
  log_usb_hid_handle_set_req__D,
  log_usb_hid_tx_cb__req_id_D,
  log_usb_hid_tx__report_D,
  log_usb_dfu_handle_get_req__D,
  log_usb_dfu_handle_set_req__D,
  log_usb_audio_is_bus_cfg_valid__D,
  //DCD----------------------------------------------------------------------------------------------------------
  log_usb_dcd_fd_notify__event_D,
  log_usb_dcd_control_transfer__is_tx_D_len_D,
  log_handle_get_descriptor__dev_dsc_len_D,
  log_handle_get_descriptor__config_dsc_len_D,
  log_handle_get_descriptor__bos_dsc_len_D,
  log_handle_get_descriptor__string_dsc_index_D,
  log_handle_get_descriptor__devqual_dsc_len_D,
  log_handle_get_descriptor__other_speed_config_dsc_len_D,
  log_handle_get_descriptor__get_hid_report_dsc_wval_D,
  log_handle_setup_ifc__req_get_interface_curr_alt_set_D,
  log_handle_setup_ifc__req_set_interface_ifc_num_D_alt_set_D,
  log_handle_setup_dev__get_status_D,
  log_handle_setup_dev__clear_feature_D,
  log_handle_setup_dev__set_feature_D,
  log_handle_setup_dev__set_isoch_delay,
  log_handle_setup_dev__get_descriptor,
  log_handle_setup_dev__get_config_D,
  log_handle_setup_ep__get_status_D,
  log_handle_setup_ep__clear_feature_D,
  log_handle_setup_ep__set_feature_D,
  log_handle_setup_ep__req_synch_frame,
  log_handle_setup_ep__call_handler_D,
  //DCI----------------------------------------------------------------------------------------------------------
  log_usb_dci_poll_events__bytes_left_D_cur_pos_D,
  log_usb_dci_handle_transfer_complete__ep_D_dir_D_event_status_D,
  log_usb_dci_handle_transfer_complete__urb_comp_idx_D_trb_comp_idx_D,
  log_usb_dci_handle_transfer_complete__zlp_phy_ep_D_urb_idx_D_trb_idx_D,
  log_usb_dci_handle_transfer_complete__urb_status_ok_urb_ptr_D_cb_ptr_D,
  log_usb_dci_submit_trb_data__ep_D_dir_D,
  log_usb_dci_submit_trb_data__trb_idx_D_trb_size_D,
  log_usb_dci_submit_trb_data__bint_n_uf_D_curr_uf_D,
  log_usb_dci_submit_trb_data__wrap_bint_n_uf_D_curr_uf_D,
  log_usb_dci_submit_trb_data__update_xfer_res_idx_D,
  log_usb_dci_prepare_trbs__ep0_dbg_trb_idx_D,
  log_usb_dci_prepare_trbs__ep_D_dir_D_trb_idx_D,
  log_usb_dci_prepare_trbs__send_zlp_ep_D_dir_D_trb_idx_D,
  log_usb_dci_transfer_request__urb_ptr_D_urb_idx_D,
  log_usb_dci_cancel_transfer__no_pending_transfer_ep_D_dir_D,
  log_usb_dci_cancel_transfer__issue_cancel_xfer_cmd_ep_D_dir_D,
  log_usb_dci_poll_pwr_event__pwr_ctrl_in_out_l2,
  log_usb_dci_poll_pwr_event__pwr_event_D,
  log_usb_dci_poll_pwr_event__pwr_ctrl_in_l2,
  log_usb_dci_poll_pwr_event__pwr_ctrl_out_l2,
  log_usb_dci_poll_pwr_event__gsi_l1_exit,
  log_usb_enable_clocks_in_isr,
  log_usb_dci_ulpi_write__reg_value_D,
  log_usb_dci_ulpi_test__ulpi_reg_read_D,
  //CLIENT_CTX----------------------------------------------------------------------------------------------------------
  log_usb_audio_lb_tx_cb__cancel,
  log_usb_audio_lb_tx_cb__status_D,
  log_usb_audio_lb_rx_cb__cancel,
  log_usb_audio_lb_rx_cb__size_D,
  log_usb_audio_lb_main__init,
  log_usb_audio_lb_main__enter_while,
  log_usb_audio_lb_main__stream_enable,
  log_usb_audio_lb_main__stream_disable,
  log_usb_audio_lb_main__disconnect,
  log_usb_audio_lb_event_cb__event_D,
  //----------------------------------------------------------------------------------------------------------
} usb_dbg_log_t;

typedef enum usb_eng_log
{
  usb_eng_log_start = 0x13000000,
  //----------------------------------------------------------------------------------------------------------
  log_usb_al_bulk__empty_fun0,
  log_usb_al_bulk__empty_fun1_var_D,
  log_usb_al_bulk2__empty_fun2_var_D_va2_D,
  log_usb_al_bulk3__empty_fun3_var_D_var2_D_var3_D,
  log_usb_al_bulk4__empty_fun1__var_D,
  log_usb_al_bulk5__empty_fun2__var_D__va2_D,
  log_usb_al_bulk6__empty_fun3__var_D__var2_D__var3_D,
  log_usb_hid_handle_set_req__D_D,
  log_usb_hid_handle_set_req_D_D,
  log_usb_hid_handle_set_req_D
  //----------------------------------------------------------------------------------------------------------
} usb_eng_log_t;

#endif /* LOG_ENUM_USB_H */
